package com.buddycloud.notifications;

public enum GCMEvent {

	FOLLOW_REQUEST, FOLLOW, UNFOLLOW, POST_AFTER_MY_POST, MENTION, POST_ON_MY_CHANNEL, 
	POST_ON_SUBSCRIBED_CHANNEL, FOLLOW_REQUEST_APPROVED, FOLLOW_REQUEST_DENIED
	
}
